import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import PrelineScript from "@/src/components/PrelineScript";
import { Provider } from "@/src/lib/Provider";
import Footer from "@/src/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>{children}</Provider>
        <Footer links={footerLinks} />
      </body>
      <PrelineScript />
    </html>
  );
}

const footerLinks = [
  {
    title: "Here to help",
    links: [
      {
        name: "Help Center",
        href: "#",
      },
      {
        name: "Contact Support",
        href: "#",
      },
      {
        name: "Status",
        href: "#",
      },
      {
        name: "Guides",
        href: "#",
      },
      {
        name: "Security",
        href: "#",
      },
    ],
  },
  {
    title: "Other ways to save",
    links: [
      {
        name: "Coupons",
        href: "#",
      },
      {
        name: "Cash Back",
        href: "#",
      },
      {
        name: "Gift Card",
        href: "#",
      },
    ],
  },

  {
    title: "Get to know us",
    links: [
      {
        name: "About Us",
        href: "#",
      },
      {
        name: "Careers",
        href: "#",
      },
      {
        name: "Blog",
        href: "#",
      },
      {
        name: "Press",
        href: "#",
      },
      {
        name: "Affiliates",
        href: "#",
      },
    ],
  },
  {
    title: "Legal stuff",
    links: [
      {
        name: "Privacy Policy",
        href: "#",
      },
      {
        name: "Terms of Use",
        href: "#",
      },
      {
        name: "Accessibility Statement",
        href: "#",
      },
      {
        name: "Do Not Sell My Personal Information",
        href: "#",
      },
    ],
  },
];
